changes in auth feature
bekaweirdo/Picnat pull request #15
Opened 2021-02-25 22:11 UTC by ted3x

2021-02-26 21:33 UTC, bekaweirdo requested changes

2021-02-26 21:33 UTC, bekaweirdo commented on app/build.gradle
> +    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.0.0'
ეს BuildSrc-ში

2021-02-26 21:33 UTC, bekaweirdo commented on core/src/main/java/com/picnat/core/data/models/User.kt
> +    @PropertyName("userId") val userId: String,
სერიალიზაციისთვის ეს ანოტაციაა საჭირო?

2021-02-26 21:33 UTC, bekaweirdo commented on core/src/main/java/com/picnat/core/network/ResponseState.kt
> +        fun <T> successWithData(data: T) = SuccessWithData(data)
success-იც და successWithData-ც უნდა იყოს?

2021-02-26 21:33 UTC, bekaweirdo commented on feature-auth/build.gradle
> +    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.0'
buildSrc

2021-02-27 18:44 UTC, ted3x commented on core/src/main/java/com/picnat/core/data/models/User.kt
> +    @PropertyName("userId") val userId: String,
ფაირბეზს სჭირდება (როგორც ჯსონ-ს აქვს ისეთი ტიპია)

2021-02-27 18:44 UTC, ted3x commented on core/src/main/java/com/picnat/core/network/ResponseState.kt
> +        fun <T> successWithData(data: T) = SuccessWithData(data)
თუ რიქვესტი დატას არ აბრუნებს კი

2021-02-27 18:58 UTC, merged